### ISSUE TITLE
Server crash after installation

### ISSUE THREAD

**Issue by cmwalsh** [emlama/meteor-foundation5-sass#15]
This is really just for your information. Every time I installed this package it would crash the local development server. The cause of this was the fact that I had the particle4dev:sass package installed. Once I removed it, your package installed just fine. The takeaway seems to be that this package is incompatible with the particle4dev:sass package.

**Comment by emlama** [comment]
Thanks for the heads up @cmwalsh. Could be the way that we're implying `fourseven:scss`, I'll dig into the docs and see if it makes sense to take that out.

**Comment by tcarlsen** [comment]
have the same problem, so wanna follow this thred

error:

```
added fourseven:scss at version 1.0.0
  added matthew:foundation5-sass at version 1.0.0

/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
TypeError: Cannot read property 'name' of undefined
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:384:34
  at Function._.each._.forEach (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:377:7
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at compileUnibuild (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:376:5)
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:1077:27
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.compiler.compile (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:1076:5)
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2004:26
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:250:13
  at [object Object]._.extend.withValue (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:243:29
  at [object Object]._.extend.withValue (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:241:18
  at [object Object]._.extend.withValue (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:232:23
  at [object Object]._.extend.withValue (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at Object.capture (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:231:19)
  at Object.exports.bundle (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1926:31)
  at bundleApp (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:509:28)
  at [object Object]._.extend._runOnce (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:527:24)
  at [object Object]._.extend._fiber (/Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:744:28)
  at /Users/tcarlsen/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:380:12
```

**Comment by emlama** [comment]
Thanks for the report @tcarlsen, I'll take a look at this later this week and see if I can reproduce and fix it. Were you also able to fix it by removing the particle4dev:sass package?

**Comment by tcarlsen** [comment]
actually I did not try.  was in a hurry so ended up using Bootstrap instead...
just wanted to give you a log for better bug tracking
